apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-service"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: game-port
    port: {{ .Values.env.gamePort | int }}
    protocol: UDP
    targetPort: {{ .Values.env.gamePort | int }}
  - name: rcon-port
    port: {{ .Values.env.rconPort | int }}
    protocol: TCP
    targetPort: {{ .Values.env.rconPort | int }}
  selector:
    app: "{{ .Chart.Name }}"

